version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template
    ports:
      - 8000:80
      - 3000:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' <
      /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"
    restart: unless-stopped
    depends_on:
      - php
      - mysqldb
  php:
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: ${APP_NAME}-php
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../:/var/www
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}-mysqldb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql

